# Generated by Django 4.1 on 2022-08-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investor",
            name="email",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
