# Generated by Django 4.1 on 2022-08-07 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_investor_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investment",
            name="startup",
        ),
        migrations.AddField(
            model_name="investment",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investments",
                to="base.offer",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="finished",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="OfferWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("curr", models.CharField(max_length=20)),
                ("balance", models.FloatField()),
                ("iban_no", models.CharField(max_length=20, unique=True)),
                ("created", models.DateTimeField(auto_now=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerwallets",
                        to="base.startup",
                    ),
                ),
            ],
        ),
    ]
