# Generated by Django 4.1 on 2022-08-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_investment_startup_investment_offer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerwallet",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offerwallets",
                to="base.offer",
            ),
        ),
    ]
