# Generated by Django 4.1 on 2022-08-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_offerwallet_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerwallet",
            name="iban_no",
            field=models.CharField(max_length=20),
        ),
    ]
