# Generated by Django 3.2.8 on 2022-08-14 07:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_offerwallet_iban_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dn3laf4bh/image/upload/v1647623057/avatar_iu9mmi.svg', max_length=255, verbose_name='image'),
        ),
    ]
