# Generated by Django 3.2.8 on 2022-08-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_investor_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
